# Site settings
title: Worm Classroom
email: webadmin@loci.wisc.edu
description: >
  Instructional Website
baseurl: "https://wormclassroom.org"
url: "https://wormclassroom.org"
github_username:  uw-loci

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
