# Site settings
title: wormclassroom.org
email: webadmin@wormclassroom.org
description: >
  WormClassroom site for C. elegans educators.
baseurl: ""
url: "http://localhost:4000"
#github_username:  SparshAgarwal

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
